[workspace]
resolver = "2"
edition = "2021"
members = ["app", "plugins/*"]


[workspace.dependencies]
bevy = { version = "0.12.1" }
bevy_mod_picking = { version = "0.17" }
bevy_mod_raycast = { version = "0.16.0" }
